#!/bin/bash
# daily-memory-log.sh — Automated Daily Memory Logging
# Version: 3.1
# Usage: ./daily-memory-log.sh [session_summary]

set -e

# Resolve V3_DIR from script location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
V3_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Date configuration
TODAY=$(date +%Y-%m-%d)
YESTERDAY=$(date -v-1d +%Y-%m-%d 2>/dev/null || date -d "yesterday" +%Y-%m-%d)
DAILY_DIR="$V3_DIR/memory/daily"
TODAY_FILE="$DAILY_DIR/$TODAY.md"

# Ensure daily directory exists
mkdir -p "$DAILY_DIR"

# Session summary from argument or default
SESSION_SUMMARY="${1:-Daily session activity}"

# Generate daily memory log
cat > "$TODAY_FILE" << EOF
# Daily Memory Log — $TODAY

**Date:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")  
**Day:** $(date +"%A")  
**Week:** $(date +"%U")  

---

## Session Summary

$SESSION_SUMMARY

## System Status

| Metric | Value |
|--------|-------|
| Quality Score | TBD |
| Context Retention | TBD |
| Cost Savings | TBD |
| Active Agents | TBD |

## Decisions Made

- [ ] No decisions recorded yet

## Facts Learned

- [ ] No facts extracted yet

## Tasks Completed

- [ ] No tasks recorded yet

## Issues Encountered

- [ ] No issues recorded yet

## Next Steps

- [ ] Review and update strategic memory

---

*Auto-generated by daily-memory-log.sh*  
*Update throughout the day as events occur*
EOF

echo "✓ Daily memory log created: $TODAY_FILE"

# Also update yesterday's file if it exists (close it out)
if [ -f "$DAILY_DIR/$YESTERDAY.md" ]; then
    echo "" >> "$DAILY_DIR/$YESTERDAY.md"
    echo "---" >> "$DAILY_DIR/$YESTERDAY.md"
    echo "" >> "$DAILY_DIR/$YESTERDAY.md"
    echo "*Session closed on $(date -u +"%Y-%m-%dT%H:%M:%SZ")*" >> "$DAILY_DIR/$YESTERDAY.md"
    echo "✓ Yesterday's log closed: $DAILY_DIR/$YESTERDAY.md"
fi

# Update state tracking
STATE_FILE="$V3_DIR/state/current.json"
if [ -f "$STATE_FILE" ]; then
    # Update last daily log timestamp
    python3 -c "
import json, sys
try:
    with open('$STATE_FILE', 'r') as f:
        state = json.load(f)
    state['last_daily_log'] = '$TODAY'
    state['last_updated'] = '$(date -u +"%Y-%m-%dT%H:%M:%SZ")'
    with open('$STATE_FILE', 'w') as f:
        json.dump(state, f, indent=2)
    print('  ✓ State updated')
except Exception as e:
    print(f'  ⚠ State update failed: {e}')
" 2>/dev/null || echo "  ⚠ State update skipped"
fi

echo ""
echo "Daily memory logging complete."
echo "File: $TODAY_FILE"
